version: "3"
services:
  nginx:
    image: nginx
    environment:
      - APP_DOMAIN=localhost
    volumes:
      - ./docker/nginx:/etc/nginx/templates
      - ./:/app:ro
    ports:
      - "80:80"
    depends_on:
      - php
    restart: unless-stopped

  php:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - mysql
      - rabbit
    restart: unless-stopped

  consumer:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    command:
      - "php"
      - "bin/console"
      - "messenger:consume"
      - "async"
      - "--limit=10"
      - "-vv"

  scheduler:
    build: ./docker/php
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    command:
      - "php"
      - "bin/console"
      - "messenger:consume"
      - "scheduler_default"
      - "--limit=10"
      - "-vv"

  mysql:
    image: mysql:8.4.5
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: unless-stopped

  rabbit:
    image: rabbitmq:3-management

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':8080'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://$APP_DOMAIN
      USE_FORWARDED_HEADERS: '1'
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw

  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "while true; do certbot renew --webroot --webroot-path /var/www/certbot/ --quiet && sleep 12h; done" ]

volumes:
###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###
